site_name: GQA

nav:
  - Home: index.md
  - Artefatos:
    - Estrutura Organizacional e de Trabalho: artefatos/estrutura-organizacional.md
    - Objetos de Auditoria: artefatos/objetos-de-auditoria.md
  - Templates:
    - N찾o Conformidades: temp/nao-conformidades.md
    - Issue N찾o Conformidade: temp/issue-de-nao-conformidade.md
    - Checklist: temp/checklist.md
    - Entrevista: temp/entrevista.md
    - Resultado do Ciclo: temp/resultado-de-ciclo.md
    - Resultado da Auditoria: temp/resultado-de-auditoria.md
  - Ferramentas:
    - Docs-Github: https://github.com/MPS-FGA/Avaleasy-GQA/tree/master/docs
    - Issues-Github: https://github.com/MPS-FGA/Avaleasy-GQA/issues
  - Processos:
    - Fluxo de Trabalho: /
    - Garantia da Qualidade:
      - Planejar Auditorias do Ciclo: /
      - Executar Auditoria: /
  - Planejamento/Resultado:
    - Ciclo 1:
      - Avaleasy:
        - Planejamento: planejamento-auditoria/planejamento-auditoria-1-avaleasy.md
        - Resuldatos:
          - Backlog: resultados-de-auditoria/auditoria-1-avaleasy/backlog.md
          - Backlog Refinado: resultados-de-auditoria/auditoria-1-avaleasy/backlog-refinado.md
          - Backlog Validado: resultados-de-auditoria/auditoria-1-avaleasy/backlog-validado.md
          - Backlog Sprint: resultados-de-auditoria/auditoria-1-avaleasy/backlog-sprint.md
          - Backlog Release: resultados-de-auditoria/auditoria-1-avaleasy/backlog-release.md
          - Backlog Release Refinado: resultados-de-auditoria/auditoria-1-avaleasy/backlog-release-refinado.md
          - Incremento: resultados-de-auditoria/auditoria-1-avaleasy/incremento.md
          - Lista Informal Requisitos: resultados-de-auditoria/auditoria-1-avaleasy/lista-informal-requisitos.md
          - Relat처rio Retrospectiva: resultados-de-auditoria/auditoria-1-avaleasy/relatorio-retrospectiva.md
          - Requisitos: resultados-de-auditoria/auditoria-1-avaleasy/requisitos.md
      - Grimorio do Mestre:
        - Planejamento: /
        - Resuldatos:
          - Backlog: /
          - Backlog Refinado: /
          - Backlog Validado: /
          - Backlog Sprint: /
          - Backlog Release: /
          - Backlog Release Refinado: /
          - Incremento: /
          - Lista Informal Requisitos: /
          - Relat처rio Retrospectiva: /
          - Requisitos: /

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'

markdown_extensions:
  - codehilite
